-- Autocmds are automatically loaded on the VeryLazy event
-- 
-- Add any autocmds here
-- with  `vim.api.vim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
